version: '3'

services:
    api:
      container_name: "api"
      build: .
      depends_on:
        - database
      ports:
        - "8080:8080"
    database:
      container_name: "postgresql"
      image: postgres
      environment:
          POSTGRES_ROOT_PASSWORD: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres
          POSTGRES_DB: smart4avation-intern
      ports:
          - "5432:5432"
      restart: always